# Generated by Django 6.0.7 on 2026-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('CL', 'Clean'), ('DI', 'Dirty'), ('IN', 'Inspected'), ('BL', 'Blocked')], default='CL', max_length=2)),
            ],
        ),
    ]
