# Generated by Django 6.0.7 on 2026-07-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
