# Generated by Django 6.0.7 on 2026-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('CL', 'Clean'), ('DI', 'Dirty'), ('IN', 'Inspected'), ('BL', 'Blocked'), ('OC', 'occupied')], default='CL', max_length=2),
        ),
    ]
