# Generated by Django 6.0.7 on 2026-08-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Classic', 'Classic')], max_length=20),
        ),
    ]
