# Generated by Django 6.0.7 on 2026-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('CL', 'Clean'), ('DI', 'Dirty'), ('IN', 'Inspected'), ('BL', 'Blocked'), ('OC', 'Occupied')], default='CL', max_length=2),
        ),
    ]
