# Generated by Django 6.0.7 on 2026-07-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('reservations', '0001_initial'),
        ('rooms', '0003_delete_guest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
