# Generated by Django 6.0.7 on 2026-07-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_reservations_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='children',
        ),
    ]
