# Generated by Django 6.0.7 on 2026-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('checkin', 'check-in'), ('checkout', 'check-out'), ('cancelled', 'Cancelled')], default='reserved', max_length=20),
        ),
    ]
